sudo: false
language: android
jdk: oraclejdk8

env:
  - ADB_INSTALL_TIMEOUT=8

android:
  components:
    - tools
    - platform-tools
    - build-tools-24.0.2
    - android-24
    - extra-android-m2repository
    - extra-google-m2repository
    - sys-img-armeabi-v7a-android-19

before_install:
  - sh script/start_emulator.sh

after_script:
  - adb logcat -d
